In [1]:
# !pip install biopython

Collecting biopython
  Downloading biopython-1.79-cp38-cp38-win_amd64.whl (2.3 MB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from biopython) (1.19.2)
Installing collected packages: biopython
Successfully installed biopython-1.79

In [1]:
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
from Bio import ExPASy
from Bio import SeqIO
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
le = preprocessing.LabelEncoder()

In [3]:
import numpy as np

In [4]:
temp = pd.read_csv('data.txt',header=None)

In [5]:
temp.columns

Int64Index([0], dtype='int64')

In [6]:
temp.columns = ['data']

In [7]:
len(temp['data'])

2

In [8]:
temp['data'][0].split(':')[0]

'Enzymes '

In [9]:
temp['data'][1].split(':')[0]

'Non enzymes '

In [10]:
len(temp['data'][0].split(':')[1])

90488

In [11]:
len(temp['data'][1].split(':')[1])

213343

In [12]:
enz_data = temp['data'][0].split(':')[1].split(' ')

In [13]:
len(enz_data)

12891

In [14]:
non_enz_data = temp['data'][1].split(':')[1].split(' ')

In [15]:
len(non_enz_data)

30376

In [16]:
enz_data = enz_data[1:]

In [17]:
non_enz_data = non_enz_data[1:]

In [18]:
enz_data[0]

'A0RIB9'

In [19]:
non_enz_data[0]

'Q8IIS5'

In [20]:
with ExPASy.get_sprot_raw("Q8IIS5") as handle:
    seq_record = SeqIO.read(handle, "swiss")
print(seq_record.id)
print(seq_record.name)
print(seq_record.description)
print(repr(seq_record.seq))
print("Length %i" % len(seq_record))
print(seq_record.annotations["keywords"])

Q8IIS5
PESC_PLAF7
RecName: Full=Pescadillo homolog {ECO:0000255|HAMAP-Rule:MF_03028}; Short=PfPES {ECO:0000303|PubMed:14698441};
Seq('MHIHKLKKKIKKKKEGKYLTKKHILRKLFLNEEEFRKLCIFKGIYPKDFKEIPL...KSK')
Length 643
['Coiled coil', 'Nucleus', 'Reference proteome', 'Ribosome biogenesis', 'rRNA processing']

In [21]:
print(seq_record.seq)

MHIHKLKKKIKKKKEGKYLTKKHILRKLFLNEEEFRKLCIFKGIYPKDFKEIPLKYRKKFYKHKVFYTRNDFLKLSHEKIINDFRKIKIYLKKYKKCKLTLEDFTRSKNIVANFPVYKLEHIIKERYPILSYAVDHLDDALSCIIAYSQLPSNHKYGIKNNMVKTCEMLKDHFHYYVYKTNRIKKAFISVKGYYLQAEILKKKVTWIIPHIFTPYLDTSIDFKLISDFIEYYIALLKFVLFKLYKLDNMLYPPKQDNDLKNEKLAHLSYDKDYSTNENNIDINMNQELQSKCNVNTNEDLNTCQEKTKEKNHKSDNNPHEHTTNIDNNNFNNIHLQDNCDLNKNEGKNLTNNIIHKNSEADNGHVHPDDHIDIDEHNKLKELFKNHIFYIHNDMPFDVLSIIILSCGGKISWNSRISPIHYDDNNITHEIYEKDKNTIHLNNPENEYKRIHIQPQYIFDCLNEKNILPCSDYLTEKENLPVHLSPFIEDENFKNLVKKEEYTINKMLNQKIKEEQYKDFSKENNNIFKSPNYKEEEEEENDDRETANLILNNKRQAALNNQLERENEDINQLKENDTILNKQTDQTQILKTQNLKSQEQEIQRHKIVLSKKKRKLFARIDMAQKRQKATIDKFMKKINKNKSK

In [24]:
seq_non_enz_data = []
n = 1
for i in non_enz_data[:600]:
    with ExPASy.get_sprot_raw(i) as handle:
        try:
            seq_non_enz_data.append(SeqIO.read(handle, "swiss"))
            print('printed', n)
            n += 1
        except:
            pass

printed 1
printed 2
printed 3
printed 4
printed 5
printed 6
printed 7
printed 8
printed 9
printed 10
printed 11
printed 12
printed 13
printed 14
printed 15
printed 16
printed 17
printed 18
printed 19
printed 20
printed 21
printed 22
printed 23
printed 24
printed 25
printed 26
printed 27
printed 28
printed 29
printed 30
printed 31
printed 32
printed 33
printed 34
printed 35
printed 36
printed 37
printed 38
printed 39
printed 40
printed 41
printed 42
printed 43
printed 44
printed 45
printed 46
printed 47
printed 48
printed 49
printed 50
printed 51
printed 52
printed 53
printed 54
printed 55
printed 56
printed 57
printed 58
printed 59
printed 60
printed 61
printed 62
printed 63
printed 64
printed 65
printed 66
printed 67
printed 68
printed 69
printed 70
printed 71
printed 72
printed 73
printed 74
printed 75
printed 76
printed 77
printed 78
printed 79
printed 80
printed 81
printed 82
printed 83
printed 84
printed 85
printed 86
printed 87
printed 88
printed 89
printed 90
printed 91
printed 92
printed 93
printed 94
printed 95
printed 96
printed 97
printed 98
printed 99
printed 100
printed 101
printed 102
printed 103
printed 104
printed 105
printed 106
printed 107
printed 108
printed 109
printed 110
printed 111
printed 112
printed 113
printed 114
printed 115
printed 116
printed 117
printed 118
printed 119
printed 120
printed 121
printed 122
printed 123
printed 124
printed 125
printed 126
printed 127
printed 128
printed 129
printed 130
printed 131
printed 132
printed 133
printed 134
printed 135
printed 136
printed 137
printed 138
printed 139
printed 140
printed 141
printed 142
printed 143
printed 144
printed 145
printed 146
printed 147
printed 148
printed 149
printed 150
printed 151
printed 152
printed 153
printed 154
printed 155
printed 156
printed 157
printed 158
printed 159
printed 160
printed 161
printed 162
printed 163
printed 164
printed 165
printed 166
printed 167
printed 168
printed 169
printed 170
printed 171
printed 172
printed 173
printed 174
printed 175
printed 176
printed 177
printed 178
printed 179
printed 180
printed 181
printed 182
printed 183
printed 184
printed 185
printed 186
printed 187
printed 188
printed 189
printed 190
printed 191
printed 192
printed 193
printed 194
printed 195
printed 196
printed 197
printed 198
printed 199
printed 200
printed 201
printed 202
printed 203
printed 204
printed 205
printed 206
printed 207
printed 208
printed 209
printed 210
printed 211
printed 212
printed 213
printed 214
printed 215
printed 216
printed 217
printed 218
printed 219
printed 220
printed 221
printed 222
printed 223
printed 224
printed 225
printed 226
printed 227
printed 228
printed 229
printed 230
printed 231
printed 232
printed 233
printed 234
printed 235
printed 236
printed 237
printed 238
printed 239
printed 240
printed 241
printed 242
printed 243
printed 244
printed 245
printed 246
printed 247
printed 248
printed 249
printed 250
printed 251
printed 252
printed 253
printed 254
printed 255
printed 256
printed 257
printed 258
printed 259
printed 260
printed 261
printed 262
printed 263
printed 264
printed 265
printed 266
printed 267
printed 268
printed 269
printed 270
printed 271
printed 272
printed 273
printed 274
printed 275
printed 276
printed 277
printed 278
printed 279
printed 280
printed 281
printed 282
printed 283
printed 284
printed 285
printed 286
printed 287
printed 288
printed 289
printed 290
printed 291
printed 292
printed 293
printed 294
printed 295
printed 296
printed 297
printed 298
printed 299
printed 300
printed 301
printed 302
printed 303
printed 304
printed 305
printed 306
printed 307
printed 308
printed 309
printed 310
printed 311
printed 312
printed 313
printed 314
printed 315
printed 316
printed 317
printed 318
printed 319
printed 320
printed 321
printed 322
printed 323
printed 324
printed 325
printed 326
printed 327
printed 328
printed 329
printed 330
printed 331
printed 332
printed 333
printed 334
printed 335
printed 336
printed 337
printed 338
printed 339
printed 340
printed 341
printed 342
printed 343
printed 344
printed 345
printed 346
printed 347
printed 348
printed 349
printed 350
printed 351
printed 352
printed 353
printed 354
printed 355
printed 356
printed 357
printed 358
printed 359
printed 360
printed 361
printed 362
printed 363
printed 364
printed 365
printed 366
printed 367
printed 368
printed 369
printed 370
printed 371
printed 372
printed 373
printed 374
printed 375
printed 376
printed 377
printed 378
printed 379
printed 380
printed 381
printed 382
printed 383
printed 384
printed 385
printed 386
printed 387
printed 388
printed 389
printed 390
printed 391
printed 392
printed 393
printed 394
printed 395
printed 396
printed 397
printed 398
printed 399
printed 400
printed 401
printed 402
printed 403
printed 404
printed 405
printed 406
printed 407
printed 408
printed 409
printed 410
printed 411
printed 412
printed 413
printed 414
printed 415
printed 416
printed 417
printed 418
printed 419
printed 420
printed 421
printed 422
printed 423
printed 424
printed 425
printed 426
printed 427
printed 428
printed 429
printed 430
printed 431
printed 432
printed 433
printed 434
printed 435
printed 436
printed 437
printed 438
printed 439
printed 440
printed 441
printed 442
printed 443
printed 444
printed 445
printed 446
printed 447
printed 448
printed 449
printed 450
printed 451
printed 452
printed 453
printed 454
printed 455
printed 456
printed 457
printed 458
printed 459
printed 460
printed 461
printed 462
printed 463
printed 464
printed 465
printed 466
printed 467
printed 468
printed 469
printed 470
printed 471
printed 472
printed 473
printed 474
printed 475
printed 476
printed 477
printed 478
printed 479
printed 480
printed 481
printed 482
printed 483
printed 484
printed 485
printed 486
printed 487
printed 488
printed 489
printed 490
printed 491
printed 492
printed 493
printed 494
printed 495
printed 496
printed 497
printed 498
printed 499
printed 500
printed 501
printed 502
printed 503
printed 504
printed 505
printed 506
printed 507
printed 508
printed 509
printed 510
printed 511
printed 512
printed 513
printed 514
printed 515
printed 516
printed 517
printed 518
printed 519
printed 520
printed 521
printed 522
printed 523
printed 524
printed 525
printed 526
printed 527
printed 528
printed 529
printed 530
printed 531
printed 532
printed 533
printed 534
printed 535
printed 536
printed 537
printed 538
printed 539
printed 540
printed 541
printed 542
printed 543
printed 544
printed 545
printed 546
printed 547
printed 548
printed 549
printed 550
printed 551
printed 552
printed 553
printed 554
printed 555
printed 556
printed 557
printed 558
printed 559
printed 560
printed 561
printed 562
printed 563
printed 564
printed 565
printed 566
printed 567
printed 568
printed 569
printed 570
printed 571
printed 572
printed 573
printed 574
printed 575
printed 576
printed 577
printed 578
printed 579
printed 580
printed 581
printed 582
printed 583
printed 584
printed 585
printed 586
printed 587
printed 588
printed 589
printed 590
printed 591
printed 592
printed 593
printed 594
printed 595
printed 596
printed 597
printed 598
printed 599

In [25]:
len(seq_non_enz_data)

599

In [67]:
seq_non_enz_data_split = []
for i in seq_non_enz_data:
    seq_non_enz_data_split.append(split(str(i.seq)))

In [77]:
seq_non_enz_data_split_500 = []
for i in seq_non_enz_data:
    seq_non_enz_data_split_500.append(split(str(i.seq)))

In [82]:
seq_non_enz_data_split_50 = []
for i in seq_non_enz_data:
    seq_non_enz_data_split_50.append(split(str(i.seq)))

In [50]:
np_seq_non_enz_data_split = np.array(seq_non_enz_data_split)

<ipython-input-50-2bc128da3706>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np_seq_non_enz_data_split = np.array(seq_non_enz_data_split)

In [51]:
np_seq_non_enz_data_split.shape

(599,)

In [83]:
with open('seq_non_enz_data_split_50.npy', 'wb') as f:
    np.save(f, np.array(seq_non_enz_data_split_50))

In [47]:
# print(seq_non_enz_data_split[0])

In [23]:
seq = []
for i in seq_non_enz_data:
    seq.append(i.seq)

In [70]:
lenth = []
for i in seq_non_enz_data_split:
    lenth.append(len(i))
min(lenth)

995

In [26]:
seq_enz_data = []
n = 1
for i in enz_data[:600]:
    with ExPASy.get_sprot_raw(i) as handle:
        try:
            seq_enz_data.append(SeqIO.read(handle, "swiss"))
            print('printed', n)
            n += 1
        except:
            pass

printed 1
printed 2
printed 3
printed 4
printed 5
printed 6
printed 7
printed 8
printed 9
printed 10
printed 11
printed 12
printed 13
printed 14
printed 15
printed 16
printed 17
printed 18
printed 19
printed 20
printed 21
printed 22
printed 23
printed 24
printed 25
printed 26
printed 27
printed 28
printed 29
printed 30
printed 31
printed 32
printed 33
printed 34
printed 35
printed 36
printed 37
printed 38
printed 39
printed 40
printed 41
printed 42
printed 43
printed 44
printed 45
printed 46
printed 47
printed 48
printed 49
printed 50
printed 51
printed 52
printed 53
printed 54
printed 55
printed 56
printed 57
printed 58
printed 59
printed 60
printed 61
printed 62
printed 63
printed 64
printed 65
printed 66
printed 67
printed 68
printed 69
printed 70
printed 71
printed 72
printed 73
printed 74
printed 75
printed 76
printed 77
printed 78
printed 79
printed 80
printed 81
printed 82
printed 83
printed 84
printed 85
printed 86
printed 87
printed 88
printed 89
printed 90
printed 91
printed 92
printed 93
printed 94
printed 95
printed 96
printed 97
printed 98
printed 99
printed 100
printed 101
printed 102
printed 103
printed 104
printed 105
printed 106
printed 107
printed 108
printed 109
printed 110
printed 111
printed 112
printed 113
printed 114
printed 115
printed 116
printed 117
printed 118
printed 119
printed 120
printed 121
printed 122
printed 123
printed 124
printed 125
printed 126
printed 127
printed 128
printed 129
printed 130
printed 131
printed 132
printed 133
printed 134
printed 135
printed 136
printed 137
printed 138
printed 139
printed 140
printed 141
printed 142
printed 143
printed 144
printed 145
printed 146
printed 147
printed 148
printed 149
printed 150
printed 151
printed 152
printed 153
printed 154
printed 155
printed 156
printed 157
printed 158
printed 159
printed 160
printed 161
printed 162
printed 163
printed 164
printed 165
printed 166
printed 167
printed 168
printed 169
printed 170
printed 171
printed 172
printed 173
printed 174
printed 175
printed 176
printed 177
printed 178
printed 179
printed 180
printed 181
printed 182
printed 183
printed 184
printed 185
printed 186
printed 187
printed 188
printed 189
printed 190
printed 191
printed 192
printed 193
printed 194
printed 195
printed 196
printed 197
printed 198
printed 199
printed 200
printed 201
printed 202
printed 203
printed 204
printed 205
printed 206
printed 207
printed 208
printed 209
printed 210
printed 211
printed 212
printed 213
printed 214
printed 215
printed 216
printed 217
printed 218
printed 219
printed 220
printed 221
printed 222
printed 223
printed 224
printed 225
printed 226
printed 227
printed 228
printed 229
printed 230
printed 231
printed 232
printed 233
printed 234
printed 235
printed 236
printed 237
printed 238
printed 239
printed 240
printed 241
printed 242
printed 243
printed 244
printed 245
printed 246
printed 247
printed 248
printed 249
printed 250
printed 251
printed 252
printed 253
printed 254
printed 255
printed 256
printed 257
printed 258
printed 259
printed 260
printed 261
printed 262
printed 263
printed 264
printed 265
printed 266
printed 267
printed 268
printed 269
printed 270
printed 271
printed 272
printed 273
printed 274
printed 275
printed 276
printed 277
printed 278
printed 279
printed 280
printed 281
printed 282
printed 283
printed 284
printed 285
printed 286
printed 287
printed 288
printed 289
printed 290
printed 291
printed 292
printed 293
printed 294
printed 295
printed 296
printed 297
printed 298
printed 299
printed 300
printed 301
printed 302
printed 303
printed 304
printed 305
printed 306
printed 307
printed 308
printed 309
printed 310
printed 311
printed 312
printed 313
printed 314
printed 315
printed 316
printed 317
printed 318
printed 319
printed 320
printed 321
printed 322
printed 323
printed 324
printed 325
printed 326
printed 327
printed 328
printed 329
printed 330
printed 331
printed 332
printed 333
printed 334
printed 335
printed 336
printed 337
printed 338
printed 339
printed 340
printed 341
printed 342
printed 343
printed 344
printed 345
printed 346
printed 347
printed 348
printed 349
printed 350
printed 351
printed 352
printed 353
printed 354
printed 355
printed 356
printed 357
printed 358
printed 359
printed 360
printed 361
printed 362
printed 363
printed 364
printed 365
printed 366
printed 367
printed 368
printed 369
printed 370
printed 371
printed 372
printed 373
printed 374
printed 375
printed 376
printed 377
printed 378
printed 379
printed 380
printed 381
printed 382
printed 383
printed 384
printed 385
printed 386
printed 387
printed 388
printed 389
printed 390
printed 391
printed 392
printed 393
printed 394
printed 395
printed 396
printed 397
printed 398
printed 399
printed 400
printed 401
printed 402
printed 403
printed 404
printed 405
printed 406
printed 407
printed 408
printed 409
printed 410
printed 411
printed 412
printed 413
printed 414
printed 415
printed 416
printed 417
printed 418
printed 419
printed 420
printed 421
printed 422
printed 423
printed 424
printed 425
printed 426
printed 427
printed 428
printed 429
printed 430
printed 431
printed 432
printed 433
printed 434
printed 435
printed 436
printed 437
printed 438
printed 439
printed 440
printed 441
printed 442
printed 443
printed 444
printed 445
printed 446
printed 447
printed 448
printed 449
printed 450
printed 451
printed 452
printed 453
printed 454
printed 455
printed 456
printed 457
printed 458
printed 459
printed 460
printed 461
printed 462
printed 463
printed 464
printed 465
printed 466
printed 467
printed 468
printed 469
printed 470
printed 471
printed 472
printed 473
printed 474
printed 475
printed 476
printed 477
printed 478
printed 479
printed 480
printed 481
printed 482
printed 483
printed 484
printed 485
printed 486
printed 487
printed 488
printed 489
printed 490
printed 491
printed 492
printed 493
printed 494
printed 495
printed 496
printed 497
printed 498
printed 499
printed 500
printed 501
printed 502
printed 503
printed 504
printed 505
printed 506
printed 507
printed 508
printed 509
printed 510
printed 511
printed 512
printed 513
printed 514
printed 515
printed 516
printed 517
printed 518
printed 519
printed 520
printed 521
printed 522
printed 523
printed 524
printed 525
printed 526
printed 527
printed 528
printed 529
printed 530
printed 531
printed 532
printed 533
printed 534
printed 535
printed 536
printed 537
printed 538
printed 539
printed 540
printed 541
printed 542
printed 543
printed 544
printed 545
printed 546
printed 547
printed 548
printed 549
printed 550
printed 551
printed 552
printed 553
printed 554
printed 555
printed 556
printed 557
printed 558
printed 559
printed 560
printed 561
printed 562
printed 563
printed 564
printed 565
printed 566
printed 567
printed 568
printed 569
printed 570
printed 571
printed 572
printed 573
printed 574
printed 575
printed 576
printed 577
printed 578
printed 579
printed 580
printed 581
printed 582
printed 583
printed 584
printed 585
printed 586
printed 587
printed 588
printed 589
printed 590
printed 591
printed 592
printed 593
printed 594
printed 595
printed 596
printed 597
printed 598
printed 599
printed 600

In [79]:
def split(word):
    word = word[:50] #+ ((500 -len(word))*'x')
    return [char for char in word]

In [64]:
seq_enz_data_split = []
for i in seq_enz_data:
    seq_enz_data_split.append(split(str(i.seq)))
# split(str(seq_enz_data[0].seq))

In [75]:
seq_enz_data_split_500 = []
for i in seq_enz_data:
    seq_enz_data_split_500.append(split(str(i.seq)))

In [80]:
seq_enz_data_split_50 = []
for i in seq_enz_data:
    seq_enz_data_split_50.append(split(str(i.seq)))

In [46]:
# print(seq_enz_data_split[0])

In [58]:
# seq_enz_data_split

In [60]:
# seq_enz_data_split[0]

In [81]:
with open('seq_enz_data_split_50.npy', 'wb') as f:
    np.save(f, np.array(seq_enz_data_split_50))

In [73]:
# seq_enz_data = seq_enz_data[:50]
len(seq_enz_data)

600

In [27]:
seq_en = []
for i in seq_enz_data:
    seq_en.append(i.seq)

In [66]:
lenth = []
for i in seq_enz_data_split:
    lenth.append(len(i))
max(lenth)

995

In [29]:
sequen = seq_en + seq

In [30]:
len(sequen)

100

In [31]:
label = list(np.zeros(50,dtype=np.int8)) + list(np.ones(50,dtype=np.int8))

In [51]:
data = pd.DataFrame()

In [32]:
col = []
for i in range(1,74):
    col.append('col'+str(i))

In [43]:
len(sequen)

100

In [44]:
dic = {}

In [49]:
m = 0
# ten = []
for i in col:
    ten = []
    for j in sequen:
        try:
            ten.append(j[m])
        except:
            ten.append('x')
    m += 1
#     print(len(ten))
    dic[i] = ten

In [52]:
for i in col:
    data[i] = dic[i]

In [53]:
len(dic['col1'])

100

In [54]:
data.head(5)

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col64,col65,col66,col67,col68,col69,col70,col71,col72,col73
0,M,N,Q,P,W,R,T,H,L,Q,...,A,I,V,C,T,R,K,Y,G,T
1,M,V,P,E,Q,N,D,L,T,E,...,R,D,L,L,V,S,L,A,D,E
2,M,A,H,A,A,A,A,T,G,A,...,S,S,T,A,A,A,A,P,P,G
3,M,L,A,G,L,S,P,H,L,S,...,L,F,L,W,N,R,S,P,R,A
4,M,D,K,L,F,S,M,I,E,V,...,E,P,L,L,C,K,N,L,D,L

In [55]:
data['label'] = label

In [57]:
data['label'].unique()

array([0, 1], dtype=int64)

In [59]:
for i in data.columns:
    data[i] = le.fit_transform(data[i])

In [60]:
data

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col65,col66,col67,col68,col69,col70,col71,col72,col73,label
0,1,9,12,12,17,13,16,6,9,12,...,7,16,1,15,14,8,17,4,15,0
1,1,15,11,3,12,11,2,9,16,3,...,2,8,9,16,15,9,0,1,3,0
2,1,0,5,0,0,0,0,16,5,0,...,15,15,0,0,0,0,10,11,5,0
3,1,8,0,5,9,14,12,6,9,14,...,4,8,18,10,14,14,10,13,0,0
4,1,1,7,9,4,14,10,7,3,16,...,12,8,9,1,8,10,8,1,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,2,8,15,0,7,5,3,13,16,...,14,0,15,5,19,13,7,13,5,1
96,1,2,1,5,3,7,3,3,5,9,...,8,14,3,7,14,3,8,8,15,1
97,1,14,13,9,9,14,0,6,14,7,...,9,8,1,9,2,11,0,1,9,1
98,1,9,4,14,13,15,7,5,3,2,...,3,16,17,9,9,9,3,8,11,1
99,1,15,15,8,3,13,11,0,0,8,...,0,14,15,0,0,8,11,14,13,1

In [63]:
X = data.drop('label', axis=1)
y = data['label']

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [66]:
model = DecisionTreeClassifier()
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [67]:
print(accuracy_score(y_test, y_pred))

0.6

In [79]:
model = RandomForestClassifier(max_depth=7, random_state=5)
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [80]:
print(accuracy_score(y_test, y_pred))

0.65

In [91]:
from sklearn import svm

In [87]:
# svm.SVC()
model = svm.SVC()
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [88]:
print(accuracy_score(y_test, y_pred))

0.6

In [92]:
from sklearn.naive_bayes import GaussianNB

In [93]:
model = GaussianNB()
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [94]:
print(accuracy_score(y_test, y_pred))

0.65

In [2]:
from sklearn.neighbors import KNeighborsClassifier

In [3]:
model = KNeighborsClassifier(n_neighbors=3)
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))

NameError: name 'X_train' is not defined

0.55